version: 2.0
jobs:
  build:
    working_directory: ~/police-scorecard
    docker:
      - image: circleci/php:7.3-stretch
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Node Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    working_directory: ~/police-scorecard
    docker:
      - image: circleci/php:7.3-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Unit Test & Code Coverage
          command: npm run -s coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy_production:
    working_directory: ~/police-scorecard
    docker:
      - image: circleci/php:7.3-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "23:e1:91:f6:bb:27:b4:16:74:68:6c:ff:58:47:7a:bf"
      - run:
          name: Deploy to Production
          command: ./.circleci/deploy-production.sh
  deploy_staging:
    working_directory: ~/police-scorecard
    docker:
      - image: circleci/php:7.3-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "23:e1:91:f6:bb:27:b4:16:74:68:6c:ff:58:47:7a:bf"
      - run:
          name: Deploy to Staging
          command: ./.circleci/deploy-staging.sh
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - staging
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - deploy_production:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only:
                - staging
