name: Police Scorecard Website Development
on:
  push:
    branches:
      - develop
jobs:
  build_and_test:
    name: Build Application and Run Tests
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Prepare The Environment
        run: |
          cp .env.ci .env
          mkdir -p bootstrap/cache
          chmod 777 bootstrap/cache

      - name: Install Composer Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          php artisan key:generate

      - name: Run Lint Tests
        run: npm run -s test-lint

      - name: Run Unit Tests
        run: npm run -s test-unit
  deploy:
    name: Deploy to Development
    runs-on: [self-hosted, linux, X64]
    needs: [build_and_test]
    steps:
      - name: Trigger Development Deployment
        run: /usr/local/bin/deploy-development
